# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Presentation/CodingGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormCoding(object):
    def setupUi(self, FormCoding):
        FormCoding.setObjectName("FormCoding")
        FormCoding.resize(768, 787)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FormCoding.setWindowIcon(icon)
        self.baseFrame = QtWidgets.QFrame(FormCoding)
        self.baseFrame.setGeometry(QtCore.QRect(10, 8, 750, 771))
        self.baseFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.baseFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.baseFrame.setObjectName("baseFrame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.baseFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 700, 731, 62))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hLayoutSave = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hLayoutSave.setContentsMargins(0, 0, 0, 0)
        self.hLayoutSave.setObjectName("hLayoutSave")
        self.btnSave = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setMinimumSize(QtCore.QSize(120, 60))
        self.btnSave.setMaximumSize(QtCore.QSize(360, 60))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/cloud-upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon1)
        self.btnSave.setIconSize(QtCore.QSize(32, 32))
        self.btnSave.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnSave.setObjectName("btnSave")
        self.hLayoutSave.addWidget(self.btnSave)
        self.grpNonCodable = QtWidgets.QGroupBox(self.baseFrame)
        self.grpNonCodable.setEnabled(True)
        self.grpNonCodable.setGeometry(QtCore.QRect(380, 540, 361, 151))
        self.grpNonCodable.setTitle("")
        self.grpNonCodable.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.grpNonCodable.setObjectName("grpNonCodable")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.grpNonCodable)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 341, 121))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.vLayoutNonCodable = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.vLayoutNonCodable.setContentsMargins(0, 0, 0, 0)
        self.vLayoutNonCodable.setObjectName("vLayoutNonCodable")
        self.rdoOtherSpeaker = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.rdoOtherSpeaker.setObjectName("rdoOtherSpeaker")
        self.vLayoutNonCodable.addWidget(self.rdoOtherSpeaker)
        self.rdoOverlappingSound = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.rdoOverlappingSound.setObjectName("rdoOverlappingSound")
        self.vLayoutNonCodable.addWidget(self.rdoOverlappingSound)
        self.rdoVegetativeSound = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.rdoVegetativeSound.setObjectName("rdoVegetativeSound")
        self.vLayoutNonCodable.addWidget(self.rdoVegetativeSound)
        self.rdoNoise = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.rdoNoise.setChecked(True)
        self.rdoNoise.setObjectName("rdoNoise")
        self.vLayoutNonCodable.addWidget(self.rdoNoise)
        self.grpSyllables = QtWidgets.QGroupBox(self.baseFrame)
        self.grpSyllables.setEnabled(True)
        self.grpSyllables.setGeometry(QtCore.QRect(380, 280, 361, 261))
        self.grpSyllables.setTitle("")
        self.grpSyllables.setObjectName("grpSyllables")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.grpSyllables)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 24, 341, 228))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.vLayoutSyllables = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.vLayoutSyllables.setContentsMargins(0, 0, 0, 0)
        self.vLayoutSyllables.setObjectName("vLayoutSyllables")
        self.vLayoutTotalSyllables = QtWidgets.QVBoxLayout()
        self.vLayoutTotalSyllables.setSpacing(0)
        self.vLayoutTotalSyllables.setObjectName("vLayoutTotalSyllables")
        self.lblTotalSyllables = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblTotalSyllables.setMinimumSize(QtCore.QSize(0, 25))
        self.lblTotalSyllables.setScaledContents(True)
        self.lblTotalSyllables.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lblTotalSyllables.setObjectName("lblTotalSyllables")
        self.vLayoutTotalSyllables.addWidget(self.lblTotalSyllables)
        self.txtTotalSyllables = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.txtTotalSyllables.setMinimumSize(QtCore.QSize(0, 25))
        self.txtTotalSyllables.setObjectName("txtTotalSyllables")
        self.vLayoutTotalSyllables.addWidget(self.txtTotalSyllables)
        self.vLayoutSyllables.addLayout(self.vLayoutTotalSyllables)
        self.vLayoutCanonicalSyllables = QtWidgets.QVBoxLayout()
        self.vLayoutCanonicalSyllables.setSpacing(0)
        self.vLayoutCanonicalSyllables.setObjectName("vLayoutCanonicalSyllables")
        self.lblCanonicalSyllables = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblCanonicalSyllables.setMinimumSize(QtCore.QSize(0, 25))
        self.lblCanonicalSyllables.setScaledContents(True)
        self.lblCanonicalSyllables.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lblCanonicalSyllables.setObjectName("lblCanonicalSyllables")
        self.vLayoutCanonicalSyllables.addWidget(self.lblCanonicalSyllables)
        self.txtCanonicalSyllables = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.txtCanonicalSyllables.setMinimumSize(QtCore.QSize(0, 25))
        self.txtCanonicalSyllables.setObjectName("txtCanonicalSyllables")
        self.vLayoutCanonicalSyllables.addWidget(self.txtCanonicalSyllables)
        self.vLayoutSyllables.addLayout(self.vLayoutCanonicalSyllables)
        self.vLayoutWordSyllables = QtWidgets.QVBoxLayout()
        self.vLayoutWordSyllables.setSpacing(0)
        self.vLayoutWordSyllables.setObjectName("vLayoutWordSyllables")
        self.lblWordSyllables = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblWordSyllables.setMinimumSize(QtCore.QSize(0, 25))
        self.lblWordSyllables.setScaledContents(True)
        self.lblWordSyllables.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lblWordSyllables.setObjectName("lblWordSyllables")
        self.vLayoutWordSyllables.addWidget(self.lblWordSyllables)
        self.txtWordSyllables = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.txtWordSyllables.setMinimumSize(QtCore.QSize(0, 25))
        self.txtWordSyllables.setObjectName("txtWordSyllables")
        self.vLayoutWordSyllables.addWidget(self.txtWordSyllables)
        self.vLayoutSyllables.addLayout(self.vLayoutWordSyllables)
        self.vLayoutWords = QtWidgets.QVBoxLayout()
        self.vLayoutWords.setSpacing(0)
        self.vLayoutWords.setObjectName("vLayoutWords")
        self.lblWords = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblWords.setMinimumSize(QtCore.QSize(0, 25))
        self.lblWords.setScaledContents(True)
        self.lblWords.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lblWords.setObjectName("lblWords")
        self.vLayoutWords.addWidget(self.lblWords)
        self.txtWords = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.txtWords.setMinimumSize(QtCore.QSize(0, 25))
        self.txtWords.setObjectName("txtWords")
        self.vLayoutWords.addWidget(self.txtWords)
        self.vLayoutSyllables.addLayout(self.vLayoutWords)
        self.grpPlayer = QtWidgets.QGroupBox(self.baseFrame)
        self.grpPlayer.setGeometry(QtCore.QRect(10, 40, 731, 241))
        self.grpPlayer.setTitle("")
        self.grpPlayer.setObjectName("grpPlayer")
        self.layoutWidget = QtWidgets.QWidget(self.grpPlayer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 711, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vLayoutPlayer = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vLayoutPlayer.setContentsMargins(0, 0, 0, 0)
        self.vLayoutPlayer.setObjectName("vLayoutPlayer")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vLayoutPlayer.addItem(spacerItem)
        self.lblUtteranceFileName = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUtteranceFileName.sizePolicy().hasHeightForWidth())
        self.lblUtteranceFileName.setSizePolicy(sizePolicy)
        self.lblUtteranceFileName.setMinimumSize(QtCore.QSize(150, 25))
        self.lblUtteranceFileName.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lblUtteranceFileName.setText("")
        self.lblUtteranceFileName.setScaledContents(False)
        self.lblUtteranceFileName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUtteranceFileName.setObjectName("lblUtteranceFileName")
        self.vLayoutPlayer.addWidget(self.lblUtteranceFileName)
        self.hLayoutSlider = QtWidgets.QHBoxLayout()
        self.hLayoutSlider.setObjectName("hLayoutSlider")
        self.lblSliderBegin = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSliderBegin.sizePolicy().hasHeightForWidth())
        self.lblSliderBegin.setSizePolicy(sizePolicy)
        self.lblSliderBegin.setObjectName("lblSliderBegin")
        self.hLayoutSlider.addWidget(self.lblSliderBegin)
        self.sldPlayer = QtWidgets.QSlider(self.layoutWidget)
        self.sldPlayer.setMinimumSize(QtCore.QSize(0, 20))
        self.sldPlayer.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sldPlayer.setMaximum(100)
        self.sldPlayer.setTracking(False)
        self.sldPlayer.setOrientation(QtCore.Qt.Horizontal)
        self.sldPlayer.setObjectName("sldPlayer")
        self.hLayoutSlider.addWidget(self.sldPlayer)
        self.lblSliderEnd = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSliderEnd.sizePolicy().hasHeightForWidth())
        self.lblSliderEnd.setSizePolicy(sizePolicy)
        self.lblSliderEnd.setObjectName("lblSliderEnd")
        self.hLayoutSlider.addWidget(self.lblSliderEnd)
        self.vLayoutPlayer.addLayout(self.hLayoutSlider)
        self.hLayoutButtons = QtWidgets.QHBoxLayout()
        self.hLayoutButtons.setSpacing(10)
        self.hLayoutButtons.setObjectName("hLayoutButtons")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayoutButtons.addItem(spacerItem1)
        self.btnPrevious = QtWidgets.QPushButton(self.layoutWidget)
        self.btnPrevious.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrevious.sizePolicy().hasHeightForWidth())
        self.btnPrevious.setSizePolicy(sizePolicy)
        self.btnPrevious.setMinimumSize(QtCore.QSize(40, 30))
        self.btnPrevious.setMaximumSize(QtCore.QSize(70, 30))
        self.btnPrevious.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Player/previous.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrevious.setIcon(icon2)
        self.btnPrevious.setIconSize(QtCore.QSize(24, 24))
        self.btnPrevious.setObjectName("btnPrevious")
        self.hLayoutButtons.addWidget(self.btnPrevious)
        self.btnPlay = QtWidgets.QPushButton(self.layoutWidget)
        self.btnPlay.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlay.sizePolicy().hasHeightForWidth())
        self.btnPlay.setSizePolicy(sizePolicy)
        self.btnPlay.setMinimumSize(QtCore.QSize(40, 30))
        self.btnPlay.setMaximumSize(QtCore.QSize(70, 30))
        self.btnPlay.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Player/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon3)
        self.btnPlay.setIconSize(QtCore.QSize(24, 24))
        self.btnPlay.setObjectName("btnPlay")
        self.hLayoutButtons.addWidget(self.btnPlay)
        self.btnNext = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext.sizePolicy().hasHeightForWidth())
        self.btnNext.setSizePolicy(sizePolicy)
        self.btnNext.setMinimumSize(QtCore.QSize(40, 30))
        self.btnNext.setMaximumSize(QtCore.QSize(70, 30))
        self.btnNext.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Player/next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon4)
        self.btnNext.setIconSize(QtCore.QSize(24, 24))
        self.btnNext.setObjectName("btnNext")
        self.hLayoutButtons.addWidget(self.btnNext)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayoutButtons.addItem(spacerItem2)
        self.vLayoutPlayer.addLayout(self.hLayoutButtons)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vLayoutPlayer.addItem(spacerItem3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.grpPlayer)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 711, 62))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.hLayoutDownload = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.hLayoutDownload.setContentsMargins(0, 0, 0, 0)
        self.hLayoutDownload.setObjectName("hLayoutDownload")
        self.btnDownload = QtWidgets.QToolButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDownload.sizePolicy().hasHeightForWidth())
        self.btnDownload.setSizePolicy(sizePolicy)
        self.btnDownload.setMinimumSize(QtCore.QSize(120, 60))
        self.btnDownload.setMaximumSize(QtCore.QSize(360, 60))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/cloud-download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDownload.setIcon(icon5)
        self.btnDownload.setIconSize(QtCore.QSize(32, 32))
        self.btnDownload.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnDownload.setObjectName("btnDownload")
        self.hLayoutDownload.addWidget(self.btnDownload)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.grpPlayer)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 190, 711, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkPlayOnly = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.chkPlayOnly.setObjectName("chkPlayOnly")
        self.horizontalLayout.addWidget(self.chkPlayOnly)
        self.lblUtteranceID = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.lblUtteranceID.setEnabled(False)
        self.lblUtteranceID.setMinimumSize(QtCore.QSize(100, 25))
        self.lblUtteranceID.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblUtteranceID.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblUtteranceID.setObjectName("lblUtteranceID")
        self.horizontalLayout.addWidget(self.lblUtteranceID)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btnLoadByID = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.btnLoadByID.setEnabled(False)
        self.btnLoadByID.setMinimumSize(QtCore.QSize(120, 25))
        self.btnLoadByID.setObjectName("btnLoadByID")
        self.horizontalLayout.addWidget(self.btnLoadByID)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.grpType = QtWidgets.QGroupBox(self.baseFrame)
        self.grpType.setEnabled(True)
        self.grpType.setGeometry(QtCore.QRect(10, 280, 361, 261))
        self.grpType.setTitle("")
        self.grpType.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.grpType.setObjectName("grpType")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.grpType)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 341, 231))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.vLayoutType = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.vLayoutType.setContentsMargins(0, 0, 0, 0)
        self.vLayoutType.setObjectName("vLayoutType")
        self.rdoLaughing = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.rdoLaughing.setObjectName("rdoLaughing")
        self.vLayoutType.addWidget(self.rdoLaughing)
        self.rdoCrying = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.rdoCrying.setObjectName("rdoCrying")
        self.vLayoutType.addWidget(self.rdoCrying)
        self.rdoNonCanonical = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.rdoNonCanonical.setObjectName("rdoNonCanonical")
        self.vLayoutType.addWidget(self.rdoNonCanonical)
        self.rdoCanonical = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.rdoCanonical.setObjectName("rdoCanonical")
        self.vLayoutType.addWidget(self.rdoCanonical)
        self.rdoWord = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.rdoWord.setObjectName("rdoWord")
        self.vLayoutType.addWidget(self.rdoWord)
        self.rdoNonCodable = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.rdoNonCodable.setChecked(True)
        self.rdoNonCodable.setObjectName("rdoNonCodable")
        self.vLayoutType.addWidget(self.rdoNonCodable)
        self.grpComments = QtWidgets.QGroupBox(self.baseFrame)
        self.grpComments.setGeometry(QtCore.QRect(10, 540, 361, 151))
        self.grpComments.setTitle("")
        self.grpComments.setObjectName("grpComments")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.grpComments)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 341, 121))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.vLayoutComment = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.vLayoutComment.setContentsMargins(0, 0, 0, 0)
        self.vLayoutComment.setSpacing(0)
        self.vLayoutComment.setObjectName("vLayoutComment")
        self.lblComments = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.lblComments.setMinimumSize(QtCore.QSize(0, 25))
        self.lblComments.setScaledContents(True)
        self.lblComments.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lblComments.setObjectName("lblComments")
        self.vLayoutComment.addWidget(self.lblComments)
        self.txtComments = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_8)
        self.txtComments.setObjectName("txtComments")
        self.vLayoutComment.addWidget(self.txtComments)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.baseFrame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 731, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hLayoutToolBar = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hLayoutToolBar.setContentsMargins(0, 0, 0, 0)
        self.hLayoutToolBar.setObjectName("hLayoutToolBar")
        self.btnList = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnList.sizePolicy().hasHeightForWidth())
        self.btnList.setSizePolicy(sizePolicy)
        self.btnList.setMinimumSize(QtCore.QSize(28, 28))
        self.btnList.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/list.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnList.setIcon(icon6)
        self.btnList.setObjectName("btnList")
        self.hLayoutToolBar.addWidget(self.btnList)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayoutToolBar.addItem(spacerItem5)
        self.lblCurrentUser = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblCurrentUser.setMinimumSize(QtCore.QSize(150, 25))
        self.lblCurrentUser.setText("")
        self.lblCurrentUser.setScaledContents(True)
        self.lblCurrentUser.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurrentUser.setObjectName("lblCurrentUser")
        self.hLayoutToolBar.addWidget(self.lblCurrentUser)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayoutToolBar.addItem(spacerItem6)
        self.btnMinimize = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMinimize.sizePolicy().hasHeightForWidth())
        self.btnMinimize.setSizePolicy(sizePolicy)
        self.btnMinimize.setMinimumSize(QtCore.QSize(28, 28))
        self.btnMinimize.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMinimize.setIcon(icon7)
        self.btnMinimize.setObjectName("btnMinimize")
        self.hLayoutToolBar.addWidget(self.btnMinimize)
        self.btnExit = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setMinimumSize(QtCore.QSize(28, 28))
        self.btnExit.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon8)
        self.btnExit.setObjectName("btnExit")
        self.hLayoutToolBar.addWidget(self.btnExit)
        self.actionUser = QtWidgets.QAction(FormCoding)
        self.actionUser.setObjectName("actionUser")
        self.actionExit = QtWidgets.QAction(FormCoding)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(FormCoding)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(FormCoding)
        QtCore.QMetaObject.connectSlotsByName(FormCoding)
        FormCoding.setTabOrder(self.btnDownload, self.btnPlay)
        FormCoding.setTabOrder(self.btnPlay, self.btnNext)
        FormCoding.setTabOrder(self.btnNext, self.btnPrevious)
        FormCoding.setTabOrder(self.btnPrevious, self.rdoLaughing)
        FormCoding.setTabOrder(self.rdoLaughing, self.rdoCrying)
        FormCoding.setTabOrder(self.rdoCrying, self.rdoNonCanonical)
        FormCoding.setTabOrder(self.rdoNonCanonical, self.rdoCanonical)
        FormCoding.setTabOrder(self.rdoCanonical, self.rdoWord)
        FormCoding.setTabOrder(self.rdoWord, self.rdoNonCodable)
        FormCoding.setTabOrder(self.rdoNonCodable, self.txtTotalSyllables)
        FormCoding.setTabOrder(self.txtTotalSyllables, self.txtCanonicalSyllables)
        FormCoding.setTabOrder(self.txtCanonicalSyllables, self.txtWordSyllables)
        FormCoding.setTabOrder(self.txtWordSyllables, self.txtWords)
        FormCoding.setTabOrder(self.txtWords, self.rdoOtherSpeaker)
        FormCoding.setTabOrder(self.rdoOtherSpeaker, self.rdoOverlappingSound)
        FormCoding.setTabOrder(self.rdoOverlappingSound, self.rdoVegetativeSound)
        FormCoding.setTabOrder(self.rdoVegetativeSound, self.rdoNoise)
        FormCoding.setTabOrder(self.rdoNoise, self.txtComments)
        FormCoding.setTabOrder(self.txtComments, self.btnSave)
        FormCoding.setTabOrder(self.btnSave, self.sldPlayer)

    def retranslateUi(self, FormCoding):
        _translate = QtCore.QCoreApplication.translate
        FormCoding.setWindowTitle(_translate("FormCoding", "VMC Coding GUI"))
        self.btnSave.setText(_translate("FormCoding", "Save"))
        self.rdoOtherSpeaker.setText(_translate("FormCoding", "Other Speaker"))
        self.rdoOverlappingSound.setText(_translate("FormCoding", "Overlapping Sound"))
        self.rdoVegetativeSound.setText(_translate("FormCoding", "Vegetative Sound"))
        self.rdoNoise.setText(_translate("FormCoding", "Noise"))
        self.lblTotalSyllables.setText(_translate("FormCoding", "Total Syllables"))
        self.txtTotalSyllables.setInputMask(_translate("FormCoding", "99"))
        self.txtTotalSyllables.setText(_translate("FormCoding", "0"))
        self.lblCanonicalSyllables.setText(_translate("FormCoding", "Canonical Syllables"))
        self.txtCanonicalSyllables.setInputMask(_translate("FormCoding", "99"))
        self.txtCanonicalSyllables.setText(_translate("FormCoding", "0"))
        self.lblWordSyllables.setText(_translate("FormCoding", "Word Syllables"))
        self.txtWordSyllables.setInputMask(_translate("FormCoding", "99"))
        self.txtWordSyllables.setText(_translate("FormCoding", "0"))
        self.lblWords.setText(_translate("FormCoding", "Words"))
        self.txtWords.setInputMask(_translate("FormCoding", "99"))
        self.txtWords.setText(_translate("FormCoding", "0"))
        self.lblSliderBegin.setText(_translate("FormCoding", "00:00"))
        self.lblSliderEnd.setText(_translate("FormCoding", "00:00"))
        self.btnDownload.setText(_translate("FormCoding", "Get New Utterance"))
        self.chkPlayOnly.setText(_translate("FormCoding", "Enable Play-Only Mode"))
        self.lblUtteranceID.setText(_translate("FormCoding", "Utterance ID#"))
        self.btnLoadByID.setText(_translate("FormCoding", "Load Uttereance"))
        self.rdoLaughing.setText(_translate("FormCoding", "Laughing"))
        self.rdoCrying.setText(_translate("FormCoding", "Crying"))
        self.rdoNonCanonical.setText(_translate("FormCoding", "Non-Canonical"))
        self.rdoCanonical.setText(_translate("FormCoding", "Canonical"))
        self.rdoWord.setText(_translate("FormCoding", "Word"))
        self.rdoNonCodable.setText(_translate("FormCoding", "Non-Codable"))
        self.lblComments.setText(_translate("FormCoding", "Comments"))
        self.actionUser.setText(_translate("FormCoding", "&User..."))
        self.actionExit.setText(_translate("FormCoding", "E&xit"))
        self.actionAbout.setText(_translate("FormCoding", "About"))


from Presentation import GuiResources
