# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Presentation/LoginForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormLogin(object):
    def setupUi(self, FormLogin):
        FormLogin.setObjectName("FormLogin")
        FormLogin.resize(320, 520)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormLogin.sizePolicy().hasHeightForWidth())
        FormLogin.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FormLogin.setWindowIcon(icon)
        FormLogin.setStyleSheet("")
        self.vLayoutMaster = QtWidgets.QVBoxLayout(FormLogin)
        self.vLayoutMaster.setObjectName("vLayoutMaster")
        self.baseFrame = QtWidgets.QFrame(FormLogin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseFrame.sizePolicy().hasHeightForWidth())
        self.baseFrame.setSizePolicy(sizePolicy)
        self.baseFrame.setMinimumSize(QtCore.QSize(300, 400))
        self.baseFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.baseFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.baseFrame.setObjectName("baseFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.baseFrame)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            277, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        self.verticalLayout.addItem(spacerItem)
        self.hLayoutLogo = QtWidgets.QHBoxLayout()
        self.hLayoutLogo.setObjectName("hLayoutLogo")
        self.lblLogo = QtWidgets.QLabel(self.baseFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogo.sizePolicy().hasHeightForWidth())
        self.lblLogo.setSizePolicy(sizePolicy)
        self.lblLogo.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblLogo.setFont(font)
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/icons/logo-white.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.hLayoutLogo.addWidget(self.lblLogo)
        self.verticalLayout.addLayout(self.hLayoutLogo)
        spacerItem1 = QtWidgets.QSpacerItem(
            277, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        self.verticalLayout.addItem(spacerItem1)
        self.hLayoutTitle = QtWidgets.QHBoxLayout()
        self.hLayoutTitle.setObjectName("hLayoutTitle")
        self.lblLogin = QtWidgets.QLabel(self.baseFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogin.sizePolicy().hasHeightForWidth())
        self.lblLogin.setSizePolicy(sizePolicy)
        self.lblLogin.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblLogin.setFont(font)
        self.lblLogin.setScaledContents(True)
        self.lblLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogin.setObjectName("lblLogin")
        self.hLayoutTitle.addWidget(self.lblLogin)
        self.verticalLayout.addLayout(self.hLayoutTitle)
        self.hLayoutCheck = QtWidgets.QHBoxLayout()
        self.hLayoutCheck.setObjectName("hLayoutCheck")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayoutCheck.addItem(spacerItem2)
        self.lblGreenCheck = QtWidgets.QLabel(self.baseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGreenCheck.sizePolicy().hasHeightForWidth())
        self.lblGreenCheck.setSizePolicy(sizePolicy)
        self.lblGreenCheck.setMinimumSize(QtCore.QSize(100, 100))
        self.lblGreenCheck.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblGreenCheck.setFont(font)
        self.lblGreenCheck.setText("")
        self.lblGreenCheck.setScaledContents(True)
        self.lblGreenCheck.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGreenCheck.setObjectName("lblGreenCheck")
        self.hLayoutCheck.addWidget(self.lblGreenCheck)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayoutCheck.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.hLayoutCheck)
        self.hLayoutUserName = QtWidgets.QHBoxLayout()
        self.hLayoutUserName.setContentsMargins(-1, 5, -1, 5)
        self.hLayoutUserName.setSpacing(5)
        self.hLayoutUserName.setObjectName("hLayoutUserName")
        self.lblUserName = QtWidgets.QLabel(self.baseFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUserName.sizePolicy().hasHeightForWidth())
        self.lblUserName.setSizePolicy(sizePolicy)
        self.lblUserName.setMaximumSize(QtCore.QSize(25, 25))
        self.lblUserName.setText("")
        self.lblUserName.setTextFormat(QtCore.Qt.RichText)
        self.lblUserName.setPixmap(QtGui.QPixmap(":/icons/user.svg"))
        self.lblUserName.setScaledContents(True)
        self.lblUserName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserName.setObjectName("lblUserName")
        self.hLayoutUserName.addWidget(self.lblUserName)
        self.txtUserName = QtWidgets.QLineEdit(self.baseFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtUserName.sizePolicy().hasHeightForWidth())
        self.txtUserName.setSizePolicy(sizePolicy)
        self.txtUserName.setMinimumSize(QtCore.QSize(240, 30))
        self.txtUserName.setToolTip("")
        self.txtUserName.setObjectName("txtUserName")
        self.hLayoutUserName.addWidget(self.txtUserName)
        self.verticalLayout.addLayout(self.hLayoutUserName)
        self.hLayoutPassword = QtWidgets.QHBoxLayout()
        self.hLayoutPassword.setContentsMargins(-1, 5, -1, 5)
        self.hLayoutPassword.setSpacing(5)
        self.hLayoutPassword.setObjectName("hLayoutPassword")
        self.lblPassword = QtWidgets.QLabel(self.baseFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPassword.sizePolicy().hasHeightForWidth())
        self.lblPassword.setSizePolicy(sizePolicy)
        self.lblPassword.setMaximumSize(QtCore.QSize(25, 25))
        self.lblPassword.setText("")
        self.lblPassword.setPixmap(QtGui.QPixmap(":/icons/lock.svg"))
        self.lblPassword.setScaledContents(True)
        self.lblPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPassword.setObjectName("lblPassword")
        self.hLayoutPassword.addWidget(self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(self.baseFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPassword.sizePolicy().hasHeightForWidth())
        self.txtPassword.setSizePolicy(sizePolicy)
        self.txtPassword.setMinimumSize(QtCore.QSize(240, 30))
        self.txtPassword.setToolTip("")
        self.txtPassword.setInputMask("")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.hLayoutPassword.addWidget(self.txtPassword)
        self.verticalLayout.addLayout(self.hLayoutPassword)
        spacerItem4 = QtWidgets.QSpacerItem(
            277, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        self.verticalLayout.addItem(spacerItem4)
        self.hLayoutButtons = QtWidgets.QHBoxLayout()
        self.hLayoutButtons.setObjectName("hLayoutButtons")
        self.btnExit = QtWidgets.QPushButton(self.baseFrame)
        self.btnExit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setMinimumSize(QtCore.QSize(130, 30))
        self.btnExit.setMaximumSize(QtCore.QSize(280, 16777215))
        self.btnExit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnExit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/close.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon1)
        self.btnExit.setIconSize(QtCore.QSize(24, 24))
        self.btnExit.setFlat(False)
        self.btnExit.setObjectName("btnExit")
        self.hLayoutButtons.addWidget(self.btnExit)
        self.btnLogin = QtWidgets.QPushButton(self.baseFrame)
        self.btnLogin.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLogin.sizePolicy().hasHeightForWidth())
        self.btnLogin.setSizePolicy(sizePolicy)
        self.btnLogin.setMinimumSize(QtCore.QSize(130, 30))
        self.btnLogin.setMaximumSize(QtCore.QSize(280, 16777215))
        self.btnLogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnLogin.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/check_mark.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogin.setIcon(icon2)
        self.btnLogin.setIconSize(QtCore.QSize(24, 24))
        self.btnLogin.setFlat(False)
        self.btnLogin.setObjectName("btnLogin")
        self.hLayoutButtons.addWidget(self.btnLogin)
        self.verticalLayout.addLayout(self.hLayoutButtons)
        spacerItem5 = QtWidgets.QSpacerItem(
            277, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding,
        )
        self.verticalLayout.addItem(spacerItem5)
        self.vLayoutMaster.addWidget(self.baseFrame)

        self.retranslateUi(FormLogin)
        QtCore.QMetaObject.connectSlotsByName(FormLogin)
        FormLogin.setTabOrder(self.txtUserName, self.txtPassword)
        FormLogin.setTabOrder(self.txtPassword, self.btnLogin)
        FormLogin.setTabOrder(self.btnLogin, self.btnExit)

    def retranslateUi(self, FormLogin):
        _translate = QtCore.QCoreApplication.translate
        FormLogin.setWindowTitle(_translate("FormLogin", "VMC Login"))
        self.lblLogin.setText(_translate("FormLogin", "Coder Login"))
        self.txtUserName.setPlaceholderText(_translate("FormLogin", "User Name"))
        self.txtPassword.setPlaceholderText(_translate("FormLogin", "Password"))


from Presentation import GuiResources
